name: Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
          cache-dependency-path: go.sum
      - name: check versions and run test
        run: make check
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: check generated CLI behaviour
        run: |
          set -e
          make install
          cd cli-test
          make cli
          make run_test
