name: Deploy
on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use --name=multiplatformbuild
          docker buildx build \
            --platform 'linux/amd64,linux/arm64' \
            --tag ghcr.io/jumpaku/cyamli-docker:latest \
            --tag ghcr.io/jumpaku/cyamli-docker:$(cat info/version.txt) \
            --push \
            .
