name: Deploy
on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        run: |
          docker buildx create --use --name=multiplatformbuild
          docker buildx build \
            --platform 'linux/amd64,linux/arm64' \
            --tag ghcr.io/Jumpaku/cyamli:latest \
            --tag ghcr.io/Jumpaku/cyamli:$(cat info/version.txt) \
            --push \
            .
